export enum UJobStatus {
  None = 0,
  Created = 1,
  Washing = 2,
  Washed = 3,
  Repairing = 4,
  Repaired = 5,
  Programming = 6,
  Programmed = 7,
  Calibrating = 8,
  Calibrated = 9,
  Labeling = 10,
  Labeled = 11,
  FieldTest = 12,
  FieldTested = 13,
  CableMeasurement_Lux = 14,
  CableMeasurement_Lux_Done = 15,
  EngraveLamps = 16,
  QCChecking = 17,
  QCChecked = 18,
  SendQuoting = 19,
  Completed = 20,
}
